name: CD Pipeline - Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image (Dry Run)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false  # 這裡設為 false: 打包測試，不推送到 DockerHub
        tags: payflow-api:latest
